name: Actualización Diaria SEACE

on:
  schedule:
    # Se ejecuta todos los días a las 8:00 AM (UTC)
    - cron: '0 8 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente

# Permisos necesarios para que el robot pueda escribir en el repositorio
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install requests pandas

      - name: Ejecutar Robot SEACE
        run: python scraper.py

      - name: Guardar cambios en GitHub
        run: |
          git config --global user.name 'Robot-Inprometal'
          git config --global user.email 'robot@inprometal.com'
          git add data.json
          git commit -m "Actualización automática: Data SEACE $(date +'%Y-%m-%d')" || echo "No hay cambios para subir"
          git push
